name: Build Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload release
      uses: Shopify/upload-to-release@v1
      with:
        name: my-artifact
        path: dist/automations-extension.js
        repo-token: ${{ secrets.GITHUB_TOKEN }}
